#!/bin/sh
# Change ALSA Master volume and optionally show notification
#
# Settings:
# simple mixer device
mixer="Master"
# notification timeout
timeout=500

# display help screen
usage() {
	echo "Usage: $0 [-h | --help] [-n] VOLUME_SETTING"
	echo "  -n          Display notifiaction"
	echo "  -h, --help  Show this message"
}

# initialize variables
curr_settings=
notification=
vol_setting=
curr_volume=

# parse commandline parameters
[ "$#" -eq "0" ] && usage && exit 1
while [ "$#" -gt "0" ]; do
	case "$1" in
		-n) notification=1;;
		-h|--help) usage; exit 0;;
		-*) usage; exit 1;;
		 *) vol_setting="$1";;
	 esac
	 shift
 done

# set volume
amixer -q set $mixer "$vol_setting"

# Get the device settings.
curr_settings=$(amixer get $mixer)

if [ -n "$notification" ]; then
	# Get volume
	curr_volume="$(echo $curr_settings | egrep -o '[0-9]+%')"
	curr_volume="${curr_volume%\%}"

	# Send notification; check whether the device is muted or not.
	if ( echo $curr_settings | grep -q "\[off\]" ); then
		notify-send -t $timeout -u low -h "int:value:$curr_volume" -h "string:synchronous:volume" "Sound volume" "ALSA Master [MUTE]"
	else
		notify-send -t $timeout -u low -h "int:value:$curr_volume" -h "string:synchronous:volume" "Sound volume" "ALSA Master"
	fi
fi
