#!/bin/sh
# Change the power state of the computer by invoking a screenlocker beforehand.
#
# Requirements:
#	systemctl (systemd)
#	a screen locker (for example i3lock or slock)

lock() {
	slock &
}

case "$1" in
	lock)
		lock;;
	logout)
		i3-msg exit;;
	suspend)
		lock && systemctl suspend;;
	hibernate)
		lock && systemctl hibernate;;
	reboot)
		systemctl reboot;;
	shutdown)
		systemctl poweroff;;
	*)
		echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
		exit 1
esac

exit 0
